### ISSUE TITLE
Also record `pid` in the output of `sonar ps`

### ISSUE THREAD

**Issue by bast** [NordicHPC/sonar#31]

**Comment by bast** [comment]
Decided not to. Explanation why not is in README.md with a3333708521f729aec7cacea.

**Comment by lars-t-hansen** [comment]
It turns out that in order to compute moment-to-moment cpu utilization the front end needs to be able to distinguish records from different processed properly, and for non-rolled-up data the (jobid, cmd) pair is insufficient. For that case, we need an additional distinguishing mark. Since we're talking about non-rolled-up data, each record represents one process and so the PID is perfect for this.  No additional information need to be stored on the sonar side, the front end can recompute what it needs.
